version: '3.7'

services:
  client:
    image: holmes89/chickaree-client:0.0.3
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      target: prod
  storage:
    image: holmes89/chickaree-storage:0.0.3
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
      target: build-env