apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chickaree.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chickaree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "chickaree.fullname" . }}-client
      labels:
        {{- include "chickaree.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.image.repository }}-client:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 6379
            protocol: TCP
          env:
          - name: STORAGE_SERVER
            value: "chickaree-storage.{{.Release.Namespace}}.svc.cluster.local:{{ .Values.rpcPort }}"
