apiVersion: v1
kind: Service
metadata:
  name: {{ include "chickaree.fullname" . }}-client
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chickaree.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chickaree.fullname" . }}-storage
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chickaree.selectorLabels" . | nindent 4 }}