apiVersion: v1
kind: Service
metadata:
  name: {{ include "chickaree.fullname" . }}-client
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}}-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chickaree.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chickaree.fullname" . }}-storage
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}-storage
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.rpcPort }}
      targetPort: {{ .Values.rpcPort }}
    - name: serf-tcp
      protocol: "TCP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
    - name: serf-udp
      protocol: "UDP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
  selector:
    {{- include "chickaree.selectorLabels" . | nindent 4 }}