apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chickaree.fullname" . }}-storage
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}-storage
spec:
  replicas: 3
  serviceName: {{include "chickaree.fullname" . }}
  selector:
    matchLabels:
      {{- include "chickaree.selectorLabels" . | nindent 6 }}-storage
  template:
    metadata:
      {{- with .Values.podAnnotations }}-storage
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chickaree.selectorLabels" . | nindent 8 }}-storage
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chickaree.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-storage
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}-storage:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.serfPort }}
              name: serf
          envFrom:
          - configMapRef:
              name: storage-config
          volumeMounts:
          - name: datadir
            mountPath: /var/run/chickaree     
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{.Values.storage}}