apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chickaree-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chickaree.labels" . | nindent 4 }}
  annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
    service-per-pod-ports: "{{.Values.rpcPort}}:{{.Values.rpcPort}}"
spec:
  replicas: 3
  serviceName: chickaree-storage
  selector:
    matchLabels:
      {{- include "chickaree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: chickaree-storage
      labels:
        {{- include "chickaree.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-storage
          image: "{{ .Values.image.repository }}-storage:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.rpcPort }}
            name: rpc
          - containerPort: {{ .Values.serfPort }}
            name: serf
          envFrom:
          - configMapRef:
              name: storage-config
          volumeMounts:
          - name: datadir
            mountPath: /var/run/chickaree     
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{.Values.storage}}